[package]
name = "char_det_ng"
version = "0.1.0"
edition = "2021"
authors = ["Jon Zeppieri <zeppieri@gmail.com>"]
publish = false

[lib]
crate-type = ["cdylib"]

[dependencies]
bytes = "1.7"
chardetng = "0.1"
encoding_rs = "0.8"
magnus = { version = "0.7", features = ["bytes"] }
